version: '3.8'
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://kc_db:5432/${POSTGRES_DB}"
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start --optimized --import-realm
    profiles: [prod]

  keycloak-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://kc_db:5432/${POSTGRES_DB}"
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start-dev --import-realm
    profiles: [dev]

  kc_db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5439:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data

volumes:
  keycloak_data:

networks:
  default:
    name: keycloak