name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    tags:
      - "v*.*.*"
  # pull_request:
    # branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: |
        echo "Running tests..."
        # Tu uruchom swoje testy
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag auth-server:$(date +%s)
